---
- name: dependencies | Install system dependencies
  sudo: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - git
    - python-dev
    - python-pip
    - python-virtualenv
    - realpath
  tags: [st2, dependencies]

- name: dependencies | Install st2 pip dependencies
  sudo: true
  pip:
    requirements: https://raw.githubusercontent.com/StackStorm/st2/master/requirements.txt
  tags: [st2, dependencies]
