---
- name: Install latest Debian st2 package (stable)
  become: yes
  apt:
    name: st2
    state: latest
  when: st2_version == "stable"
  notify:
    - restart st2

- name: Install latest Debian st2 package (not stable)
  become: yes
  apt:
    name: st2={{ st2_version }}-{{ st2_revision }}
    state: present
  when: st2_version != "stable"
  notify:
    - restart st2
