- name: Install system dependencies
  sudo: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - git
    - python-dev
    - python-setuptools

- name: Install pip
  sudo: true
  easy_install:
    name: pip

- name: Get global requirements
  get_url:
    url: https://raw.githubusercontent.com/StackStorm/st2/master/requirements.txt
    dest: /tmp/requirements.txt
  register: global_requirements

- name: Install global requirements
  sudo: true
  pip:
    requirements: "{{ global_requirements.dest }}"

- name: Fetch release number
  get_url:
    url: "https://downloads.stackstorm.net/releases/st2/{{ _st2_version }}/debs/{{ st2_revision }}/VERSION.txt"
    dest: /tmp/release
    force: yes
  register: release_request

- name: Read release number
  shell: cat {{ release_request.dest }}
  register: release

- name: Make temp directory
  file:
    path: /tmp/st2/{{ _st2_version }}/debs/{{ release.stdout }}
    state: directory

- name: Download packages
  get_url:
    url: "https://downloads.stackstorm.net/releases/st2/{{ _st2_version }}/debs/{{ st2_revision }}/{{ item }}_{{ _st2_version }}-{{ release.stdout }}_amd64.deb"
    dest: /tmp/st2/{{ _st2_version }}/debs/{{ release.stdout }}/{{ item }}_{{ _st2_version }}-{{ release.stdout }}_amd64.deb
  with_items: st2_packages
  register: package_files

- name: Install packages
  sudo: true
  apt:
    deb: "{{ item.dest }}"
  with_items: package_files.results
  #when: package_files.changed

- name: Chown logs directory
  sudo: true
  file:
    path: /var/log/st2
    owner: "{{ st2_system_user }}"
    group: "{{ st2_system_user }}"
    recurse: yes
