---
- name: Install latest st2 package
  become: yes
  apt:
    name: st2
    state: latest
  when: st2_version == "latest"
  notify:
    - restart st2
  tags: skip_ansible_lint

- name: Install latest st2 package
  become: yes
  apt:
    name: st2={{ st2_version }}-{{ st2_revision }}
    state: present
  when: st2_version != "latest"
  notify:
    - restart st2

- name: Create and configure StackStorm system user
  include: user.yml

- name: Configure StackStorm authentication
  include: config_auth.yml
  when: st2_auth_enable

- name: Ensure StackStorm services are enabled and running
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ st2_services }}"