---
- name: Install latest Debian st2 package (stable)
  become: yes
  package:
    name: st2
    state: latest
    disable_gpg_check: yes
  when: st2_version == "stable"
  notify:
    - restart st2

- name: Install latest Debian st2 package (not stable)
  become: yes
  package:
    name: st2={{ st2_version }}-{{ st2_revision }}
    state: present
    disable_gpg_check: yes
  when: st2_version != "stable"
  notify:
    - restart st2

- include: user.yml

- include: config_auth.yml
  when: enable_auth
