- include: 1.requirements.yml
- include: 2.version.yml
- include: 3.user.yml

- include: install.yml
- include: config.yml

- name: Register content
  shell: "python /usr/lib/python2.7/dist-packages/st2common/bin/st2-register-content
          --config-file /etc/st2/st2.conf --register-all 2>&1"
